# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: oiumze/oiumze-site

media_folder: /public/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: /content/posts
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, time_format: false }
      - { label: Body, name: body, widget: richtext }
  - name: gallery
    label: Galeria de Fotos
    label_singular: Foto
    folder: /content/gallery
    create: true
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Imagem, name: image, widget: image }